"""init

Revision ID: d8f300eaa412
Revises: 
Create Date: 2023-01-26 19:09:59.908925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8f300eaa412'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
                sa.Column('id', sa.Integer(), nullable=False),
                sa.Column('name', sa.String(), nullable=False),
                sa.PrimaryKeyConstraint('id')
                )
    op.create_table('tag',
                sa.Column('id', sa.Integer(), nullable=False),
                sa.Column('name', sa.String(), nullable=False),
                sa.PrimaryKeyConstraint('id')
                )
    op.create_table('book',
                sa.Column('id', sa.Integer(), nullable=False),
                sa.Column('name', sa.String(), nullable=False),
                sa.Column('category_id', sa.Integer(), nullable=True),
                sa.Column('tag_id', sa.Integer(), nullable=True),
                sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
                sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
                sa.PrimaryKeyConstraint('id')
                )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book')
    op.drop_table('tag')
    op.drop_table('category')
    # ### end Alembic commands ###
